#!/bin/sh

D3GPIO=/sys/class/gpio/gpio17
J8GPIO=/sys/class/leds/carambola2\:green\:wlan

case "$1" in
        D3)
                if [ ! -d "$D3GPIO" ]; then
                        echo 17 > /sys/class/gpio/export
                fi
                echo 'out' > $D3GPIO/direction
                case "$2" in
                        on)
                                echo 1 > $D3GPIO/value
                                ;;
                        off)
                                echo 0 > $D3GPIO/value
                                ;;
                esac
                ;;
        J8)
                echo 'none' > $J8GPIO/trigger
                case "$2" in
                        on)
                                echo 1 > $J8GPIO/brightness
                                ;;
                        off)
                                echo 0 > $J8GPIO/brightness
                                ;;
                esac
                ;;
esac
