#!/bin/sh                                                                       
            
/sbin/ifconfig can0 up

# Test basic motor function                                                     
if [ -z "$1" ]                                                                  
  then                                                                          
        echo 'Motor id 1 or 2 required as argument'                             
        exit 1                                                                  
fi                                                                              
MOTOR_ID=$1                                                                     
                                                                                
echo "Motor:$MOTOR_ID"                                                          
/usr/bin/motor-cli --set_id $MOTOR_ID --run                                     
                                                                                
VERSION=$(/usr/bin/motor-cli --set_id $MOTOR_ID --get_ver)                    
echo "Firmware:$VERSION"                                                        
                                                                                
echo "Setting position:0"                                                       
/usr/bin/motor-cli --set_id $MOTOR_ID --set_pos 0                               
                                                                                
echo "Move: 10000"                                                              
/usr/bin/motor-cli --set_id $MOTOR_ID --move 10800,3000      
sleep 5                      
                                                                                
POSITION=$(/usr/bin/motor-cli --set_id $MOTOR_ID --get_pos)                   
echo "Position:$POSITION"                                                       
                                                                                
echo "Move: 0"                                                                  
/usr/bin/motor-cli --set_id $MOTOR_ID --move -800,3000                             
sleep 5                      
                                                                                                                                                                
POSITION=$(/usr/bin/motor-cli --set_id $MOTOR_ID --get_pos)                    
echo "Position:$POSITION"                                                       
                                        