#!/bin/sh /etc/rc.common
# This will tracker controller
# Save this file as /etc/init.d/tc
# Add execute to permissions chmod +x /etc/init.d/tc
# Use /etc/init.d/tc enable to setup the rc.d files using this file.

#START=99
STOP=5

start() {
	/usr/bin/rla-bin &
}

stop() {
	/usr/bin/killall rla-bin
}

